
import javax.swing.ImageIcon;

public class VisuJoueurDlg extends javax.swing.JDialog {

    Joueur Jsave;

    public VisuJoueurDlg(java.awt.Frame parent, boolean modal, Joueur j) {
        super(parent, modal);
        this.Jsave = j;
        initComponents();
        zonePseudo.setText(j.getPseudo());
        zoneColor.setBackground(j.getCouleur());
        zoneSolde.setText(j.getSolde() + "€");
        //affichage des Lots
        if (j.getMesLots().getTaille() > 0) {
            gifts.setText(j.getMesLots().toString());
        } else {
            gifts.setText("Aucun lot");
        }
        //Active ou desactive la modification en fonction de si le joueur a déjà des cartes
        if (j.getMesCartes().getTaille() > 0) {
            Modifier.setEnabled(false);
        }
        //Si pas de photos en met une par défaut
        if (j.getPhoto() == null) {
            j.setPhoto(new ImageIcon(getClass().getResource("/imgs/defaultImg.png")));
        }
        mainRigth.add(new PanneauImage(j.getPhoto()));
    }

    public VisuJoueurDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NORTH = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        CENTER = new javax.swing.JPanel();
        LEFT = new javax.swing.JPanel();
        mainLeft = new javax.swing.JPanel();
        pseudo = new javax.swing.JLabel();
        zonePseudo = new javax.swing.JLabel();
        couleur = new javax.swing.JLabel();
        zoneColor = new javax.swing.JTextField();
        solde = new javax.swing.JLabel();
        zoneSolde = new javax.swing.JLabel();
        secondLeft = new javax.swing.JPanel();
        Modifier = new javax.swing.JButton();
        RIGHT = new javax.swing.JPanel();
        mainRigth = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gifts = new javax.swing.JTextArea();
        secondRigth = new javax.swing.JPanel();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));
        setPreferredSize(new java.awt.Dimension(500, 300));

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("Information relative à un joueur");
        NORTH.add(title);

        getContentPane().add(NORTH, java.awt.BorderLayout.NORTH);

        CENTER.setLayout(new java.awt.GridLayout(1, 2));

        LEFT.setLayout(new java.awt.BorderLayout());

        mainLeft.setLayout(new java.awt.GridLayout(3, 2));

        pseudo.setText("Pseudo");
        mainLeft.add(pseudo);
        mainLeft.add(zonePseudo);

        couleur.setText("Couleur");
        mainLeft.add(couleur);

        zoneColor.setEditable(false);
        zoneColor.setAutoscrolls(false);
        zoneColor.setBorder(null);
        zoneColor.setFocusable(false);
        mainLeft.add(zoneColor);

        solde.setText("Solde");
        mainLeft.add(solde);
        mainLeft.add(zoneSolde);

        LEFT.add(mainLeft, java.awt.BorderLayout.CENTER);

        secondLeft.setLayout(new java.awt.GridLayout(1, 0));

        Modifier.setText("Modifier");
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });
        secondLeft.add(Modifier);

        LEFT.add(secondLeft, java.awt.BorderLayout.SOUTH);

        CENTER.add(LEFT);

        RIGHT.setLayout(new java.awt.BorderLayout());

        mainRigth.setLayout(new java.awt.GridLayout(1, 2));

        gifts.setEditable(false);
        gifts.setColumns(20);
        gifts.setRows(5);
        gifts.setAutoscrolls(false);
        gifts.setFocusable(false);
        jScrollPane1.setViewportView(gifts);

        mainRigth.add(jScrollPane1);

        RIGHT.add(mainRigth, java.awt.BorderLayout.CENTER);

        secondRigth.setLayout(new java.awt.GridLayout(1, 0));

        close.setText("Fermer");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        secondRigth.add(close);

        RIGHT.add(secondRigth, java.awt.BorderLayout.SOUTH);

        CENTER.add(RIGHT);

        getContentPane().add(CENTER, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        dispose();
    }//GEN-LAST:event_closeActionPerformed

    //Ouvre la JDialog AjoutJoueurs en rentrant le joueur concerné pour pouvoir le modifier
    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
        AjoutJoueurDlg modifJoueur = new AjoutJoueurDlg(this, true, this.Jsave);
        modifJoueur.setVisible(true);
        if (modifJoueur.getOK()) {
            Jsave.setPseudo(modifJoueur.getPseudo());
            Jsave.setCouleur(modifJoueur.getCouleur());
            Jsave.setPhoto(modifJoueur.getPhoto());
            zonePseudo.setText(Jsave.getPseudo());
            zoneColor.setBackground(Jsave.getCouleur());
            PanneauImage tmp = (PanneauImage) mainRigth.getComponent(1);
            tmp.setImage(Jsave.getPhoto());
        }
    }//GEN-LAST:event_ModifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisuJoueurDlg dialog = new VisuJoueurDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CENTER;
    private javax.swing.JPanel LEFT;
    private javax.swing.JButton Modifier;
    private javax.swing.JPanel NORTH;
    private javax.swing.JPanel RIGHT;
    private javax.swing.JButton close;
    private javax.swing.JLabel couleur;
    private javax.swing.JTextArea gifts;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainLeft;
    private javax.swing.JPanel mainRigth;
    private javax.swing.JLabel pseudo;
    private javax.swing.JPanel secondLeft;
    private javax.swing.JPanel secondRigth;
    private javax.swing.JLabel solde;
    private javax.swing.JLabel title;
    private javax.swing.JTextField zoneColor;
    private javax.swing.JLabel zonePseudo;
    private javax.swing.JLabel zoneSolde;
    // End of variables declaration//GEN-END:variables
}
